config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/sign_in', to: 'users#new' 
  post '/sign_in', to: 'users#create' 

  # get '/login', to: 'sessions#new' 
  # post '/login', to: 'sessions#create' 
  # get '/logout', to: 'sessions#destroy'
  
  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create', as: 'sessions' 
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  # resources :articles, except: [:destroy] do 
  #   resources :comments, only: [:create, :edit, :update] 
  # end
  resources :articles do 
    resources :comments, only: [:create, :edit, :update] do
      get 'edit', on: :member 
      resources :replies, only: [:new, :create] 
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  # has_many :replies, dependent: :destroy
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	# before_action :require_login, except: [:index, :show] 
	before_action :require_login, only: [:index, :show] 
	before_action :authorize_edit, only: [:edit, :update]
	
	def new
		@article = Article.find(params[:article_id])
		@comment = @article.comments.new
	end

	def create
		@article = Article.find(params[:article_id]) 
		@comment = @article.comments.build(comment_params) 
		@comment.user = current_user 
		if @comment.save 
			redirect_to @article, notice: 'Comment created successfully!'
		else 
			flash.now[:alert] = 'Comment could not be created!'
			render 'articles/show'
			# render :new, status: :unprocessable_entity
		end
	end
	
	def edit
		@article = Article.find(params[:article_id]) 
		@comment = @article.comments.find(params[:id]) 
		authorize_edit
		if current_user != @comment.user
			redirect_to @article, alert: 'You are not authorized to edit this comment!'
		end
	end
	
	def update
		@article = Article.find(params[:article_id]) 
		@comment = @article.comments.find(params[:id]) 
		# @comment.user = current_user 
		authorize_edit
		if current_user == @comment.user && @comment.update(comment_params)
			redirect_to @article, notice: 'Comment updated successfully!'
		else 
			flash.now[:alert] = 'Comment could not be updated!'
			render :edit
		end
	end
	
	private
	
	def comment_params 
		params
			.require(:comment)
			.permit(:content, :parent_id)
			.merge(article_id: params[:article_id])
	end

	def require_login
		unless current_user 
			flash[:error] = "You must be logged in to access this page." 
			redirect_to root_path 
		end
	end

	def authorize_edit
		# unless current_user == @comment.user 
		# 	redirect_to root_path, alert: 'You are not authorized to perform this action.'
		# end

		@article = Article.find(params[:article_id]) 
		@comment = @article.comments.find(params[:id]) 
		# @comment = current_user.articles.comments.find_by(id: params[:id]) 

		if @comment.nil?
			flash[:alert] = "Comment not found." 
			redirect_to root_path
		elsif @comment.user != current_user 
			flash[:alert] = "You are not authorized to edit this comment." 
			redirect_to root_path
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<article>
	<p><%= comment.content %></p>
	<small>by <%= comment.user.email %></small>

	<% if comment.persisted? %>
		<% if current_user == comment.user %>
			<%= link_to "Edit", "#", class: "comment-form-display", data: { form: "edit-form-#{comment.id}" } %>
		<% elsif current_user == comment.article.user %>
			<%= link_to "Reply", "#", class: "comment-form-display", data: { form: "reply-form-#{comment.id}" } %>
		<% end %>
		<div class="comment-form" id="edit-form-<%= comment.id %>" style="display: none;">
			<%= render partial: 'comments/edit', locals: { article: @article, comment: comment } %>
		</div>
		<div class="comment-form" id="reply-form-<%= comment.id %>" style="display: none;">
			<%= render partial: 'comments/form', locals: { article: comment.article, parent: comment } %>
		</div>
	<% end %>
	

	<div class="comment-form">
		<%= render partial: 'comments/form', locals: {article: comment.article, parent: comment}%>
	</div>
	<hr />
	<div class="sub-comment">
		<%= render comment.comments.order(id: :desc) %>
	</div>
</article>

<script>
	document.querySelectorAll('.comment-form-display').forEach((el) => {
		el.addEventListener('click', (ev) => {
			ev.preventDefault();
			const formId = el.getAttribute('data-form');
			document.getElementById(formId).style.display = 'block';
		})
	})

</script>

app/views/comments/_edit.html.erb
<h1>Edit Comment</h1>

<%= form_with(model: [article, comment], url: article_comment_path(article, comment), method: :patch) do |form| %>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit 'Update Comment' %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<form action="<%= article_comments_path(@article) %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<% if !parent.nil? %>
		<input type="hidden" name="comment[parent_id]" value="<%= parent.id %>">
	<% end %>
	<textarea name="comment[content]" rows="6" cols="20"></textarea>
	<input type="submit" value="Submit">
</form>

app/views/comments/_reply.html.erb
<div class="reply">
	<p><strong><%= reply.user.name %></strong>: <%= reply.content %></p>
</div>