config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/sign_in', to: 'users#new' 
  post '/sign_in', to: 'users#create' 

  # get '/login', to: 'sessions#new' 
  # post '/login', to: 'sessions#create' 
  # get '/logout', to: 'sessions#destroy'
  
  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create', as: 'sessions' 
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  # resources :articles, except: [:destroy] do 
  #   resources :comments, only: [:create, :edit, :update] 
  # end
  resources :articles do 
    resources :comments, only: [:create, :edit, :update] do
      get 'edit', on: :member 
      resources :replies, only: [:new, :create] 
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true 
  validates :content, presence: true, length: {minimum: 10} 
  enum visibility: { draft: 'draft', public: 'public' }, _prefix: true
  # enum visibility: { draft: 'draft', public: 'public' }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# before_action :require_login, except: [:index, :show]
	before_action :require_login, only: [:show]  
	before_action :authorize_edit, only: [:edit, :update] 
	
	def index
		# debugger
		@articles = Article.all
		# @articles = Article.where(visibility: :public)
		# if current_user
		# 	@articles = Article.where(visibility: [:public, :draft], user: [current_user, nil])
		# 	@articles = Article.where(visibility: :public).or(Article.where(user: current_user, visibility: :draft))
		# else
		# 	@articles = Article.where(visibility: :public)
		# end
	end
	
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new 
		@comment.user = current_user 
	end
	
	def new
		@article = current_user.articles.build
	end
	
	def create
		@article = current_user.articles.build(article_params)
		# debugger
		if params[:commit] == 'Create Article'
			@article.visibility = 'public'
		else
			@article.visibility = 'draft'
		end
	
		if @article.save
			redirect_to @article, notice: 'Article created successfully!'
		else
			render :new, status: :unprocessable_entity
		end
	end
	
	def edit
		@article = current_user.articles.find(params[:id]) 
	end

	def destroy
		@article = current_user.articles.find(params[:id]) 
		@article.destroy
		redirect_to @article, notice: 'Article deleted successfully!'
	end

	def update
		@article = current_user.articles.find(params[:id]) 
		if @article.update(article_params) 
			redirect_to @article, notice: 'Article updated successfully!'
		else 
			render :edit, status: :unprocessable_entity
		end
	end
	
	private
	
	def article_params 
		params.require(:article).permit(:title, :content, :visibility) 
		# params.require(:article).permit(:title, :content, :visibility)
		# 	.tap { |p| p[:visibility] = "draft" if params[:commit] == "Save Draft" }
	end

	def require_login
		unless current_user 
			flash[:error] = "You must be logged in to access this page." 
			redirect_to root_path 
		end
	end

	def authorize_edit
		@article = current_user.articles.find_by(id: params[:id]) 

		if @article.nil?
			flash[:alert] = "Article not found." 
			redirect_to root_path
		elsif @article.user != current_user 
			flash[:alert] = "You are not authorized to edit this article." 
			redirect_to root_path
		end
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <!-- Title and Content fields -->
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :title %>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :content %>
    </div>
    <div class="col-sm-6">
      <%= f.text_area :content, rows: 10, class: "form-control", placeholder: "Body of Article" %>
    </div>
  </div>

  <!-- Visibility field -->
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :visibility %>
    </div>
    <div class="col-sm-6">
      <%= f.select :visibility, [['Public', 'public'], ['Draft', 'draft']], {}, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <%= f.submit 'Create Article', class: 'btn btn-primary' %>
        <%= button_tag 'Save Draft', type: 'submit', class: 'btn btn-primary draft-btn', name: 'commit', value: 'Save Draft' %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render 'layouts/navigation' %>
<h1>Edit Existing Article</h1>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<%= render 'layouts/navigation' %>
<% if current_user %>
  Hello <%= current_user.email %>
<% end %>

<h1 align="center">Listing all articles</h1>

<% @articles.each do |article| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title">
					<%= link_to article.title, article_path(article) %>
				</div>
				<div class="article-body">
					<%= truncate(article.content, length: 100) %>
				</div>
				<% if article.user == current_user && article.visibility == "draft" %>
					<div class="article-actions">
						<%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
						<%= link_to "Delete", article_path(article), method: :delete, turbo_data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
					</div>
				<% elsif article.visibility == "public" && article.user == current_user %>
					<div class="article-actions">
						<%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
						<%= link_to "Delete", article_path(article), method: :delete, turbo_data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
					</div>
				<% elsif article.visibility == "public" && article.user != current_user  %>
					<div class="article-actions">
						<%= link_to "View", article_path(article), class: "btn btn-xs btn-primary" %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/articles/new.html.erb
<%= render 'layouts/navigation' %>
<h1 align="center">Create New Article</h1>
<%= render "form", post: @article %>

app/views/articles/show.html.erb
<%= render 'layouts/navigation' %>

<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.content) %>
  <% if @article.user == current_user %>
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", article_path(@article), turbo_method: :delete, data: {
      turbo_method: "DELETE",
      turbo_confirm: "Are you sure?"
        }, class: "btn btn-xs btn-danger" %>
  <% end %>
  <%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>

<p> 
  <h2>Comments:</h2>

  <%= render @article.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
  <%= render partial: 'comments/form', locals: { article: @article, parent: nil } %> 
  <%= render partial: 'comments/comment', locals: { comment: @comment } %> 
</p>