config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/sign_in', to: 'users#new' 
  post '/sign_in', to: 'users#create' 

  # get '/login', to: 'sessions#new' 
  # post '/login', to: 'sessions#create' 
  # get '/logout', to: 'sessions#destroy'
  
  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create', as: 'sessions' 
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  # resources :articles, except: [:destroy] do 
  #   resources :comments, only: [:create, :edit, :update] 
  # end
  resources :articles do 
    resources :comments, only: [:create, :edit, :update] do
      get 'edit', on: :member 
      resources :replies, only: [:new, :create] 
    end
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Kavya's Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> 
			<ul class="nav navbar-nav">
				<li><%= link_to "Article", articles_path %></li>
				<li><%= link_to "Create Article", new_article_path %></li>
				<li><%= link_to "Sign Out", logout_path %></li>
			</ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticlePostApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
    
  <body>
      <%= yield %> 
  </body>
</html>
    
    